version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - mynetwork

  postgres:
    image: postgres:16
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork: